[package]
name = "aoc-stats-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls-webpki-roots", "http2", "blocking", "gzip"] }
tl = "0.7.8"
